### PR TITLE
fix: fix link

### PR DESCRIPTION
**Pull request by hituzi-no-sippo**
I read [oss-contribution-guide](https://github.com/suzuki-shunsuke/oss-contribution-guide).

[It says that "typo fixes" don't need to create a issue](https://github.com/suzuki-shunsuke/oss-contribution-guide#create-an-issue-before-creating-a-pull-request), so I think this pull request doesn't need to create a issue either.

Thank you.

### CODE REVIEW

**Comment by suzuki-shunsuke** [comment]
Thank you for your contribution!

> [It says that "typo fixes" don't need to create a issue](https://github.com/suzuki-shunsuke/oss-contribution-guide#create-an-issue-before-creating-a-pull-request), so I think this pull request doesn't need to create a issue either.

Yes. That's correct.

But I think the link isn't broken and works as expected, so we don't have to fix the link.

https://aquaproj.github.io/docs/reference/registry-style-guide

image

**Comment by hituzi-no-sippo** [comment]
Thank you for response.

This occurs when accessing "Registry Style Guide"(https://aquaproj.github.io/docs/reference/registry-style-guide/) directly.
It does not occur when do not directly access  "Registry Style Guide".

## Chrome

https://user-images.githubusercontent.com/43565959/210170754-9046eb4b-7d96-43d3-a803-9cf9dfe80be0.mp4

## Edge

https://user-images.githubusercontent.com/43565959/210170756-9d98d6a3-dd0a-4ee9-8ea8-3ee319220b17.mp4

OS: Windows 10 Home
Version: 22H2
OS build: 19045.2364

**Comment by suzuki-shunsuke** [comment]
Oh, I see. Thank you for your explanation.
I could reproduce the issue.

This problem would occur if the suffix of URL is `/`, because the relative path would change by the suffix `/`.

* https://aquaproj.github.io/docs/reference/registry-style-guide => https://aquaproj.github.io/docs/reference/scaffold-registry :o:
* https://aquaproj.github.io/docs/reference/registry-style-guide/ => https://aquaproj.github.io/docs/reference/registry-style-guide/scaffold-registry :x:

So this pr would solve the problem.
But I'd like to take a look another solution a bit, because the relative path is sometimes useful.

**Comment by suzuki-shunsuke** [comment]
https://docusaurus.io/docs/markdown-features/links

**Comment by suzuki-shunsuke** [comment]
Even if we set `trailingSlash: false`, we can still access to URLs with the suffix `/`, which means `trailingSlash: false` doesn't solve the issue completely.

https://docusaurus.io/docs/api/docusaurus-config#trailingSlash

**Comment by suzuki-shunsuke** [comment]
https://docusaurus.io/docs/markdown-features/links

> Using relative file paths (with .md extensions) instead of relative URL links provides the following benefits:

I've confirmed relative file paths would solve this issue.

**Comment by suzuki-shunsuke** [comment]
Thanks!

**Comment by suzuki-shunsuke** [comment]
- https://github.com/aquaproj/aquaproj.github.io/pull/232

**Pull request merged**
